/**
 * AiAlert Schema
 *
 * Represents an automated risk alert proposed by the AI Anomaly Detection service.
 * Generated when time-series indicators cross baseline anomaly thresholds or
 * when fused with official weather forecasts.
 *
 * Researchers and SDMA operators can review the time-series charts, anomaly scores,
 * and natural-language explanations, then either:
 *   - "Promote" it directly into a DisasterEvent for publication
 *   - "Dismiss" it as a false alarm / benign anomaly
 */

const mongoose = require('mongoose');

const AI_ALERT_STATUSES = [
  'pending_review',
  'approved_into_event',
  'dismissed',
  'escalated',
  'approved',
  'rejected',
];

const aiAlertSchema = new mongoose.Schema(
  {
    state: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },

    district: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },

    hazardType: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },

    // Anomaly confidence / severity score: 0.0 (normal) to 1.0 (extreme anomaly)
    score: {
      type: Number,
      required: true,
      min: 0,
      max: 1,
      index: true,
    },

    threshold: {
      type: Number,
      default: 0.65,
    },

    recommendedSeverity: {
      type: String,
      enum: ['Advisory', 'Watch', 'Warning', 'Emergency', 'Low', 'Medium', 'High', 'Critical'],
      default: 'Watch',
    },

    // Whether this alert was generated by predictive ML forecasting (nowcasting)
    isPredictive: {
      type: Boolean,
      default: false,
      index: true,
    },

    // Prediction horizon window (e.g., '1h', '3h', '6h')
    predictionHorizon: {
      type: String,
      default: null,
    },

    // Raw ML model predictions and confidence metadata
    predictionDetails: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // Contributing features that caused the alert
    anomalyFeatures: [
      {
        indicator: String,
        currentValue: Number,
        baselineMean: Number,
        baselineStd: Number,
        deviationScore: Number, // z-score or percentage above normal
        unit: String,
      },
    ],

    // Human-readable explanation generated by AI
    // e.g., "Rainfall (115 mm) is 3.4 standard deviations above 30-day baseline; Ganga river gauge at Varanasi is 0.4m above Warning Mark."
    explanation: {
      type: String,
      required: true,
      trim: true,
      maxlength: 1500,
    },

    // Optional suggested safety steps
    suggestedActions: [String],

    // Forecast and hydrological metrics from Open-Meteo & IMD
    forecastData: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    // Composite & component risk probabilities
    riskScores: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    capUrgency: {
      type: String,
      default: 'Future',
    },

    capSeverity: {
      type: String,
      default: 'Watch',
    },

    // Geographic coordinates of focal danger zone
    suggestedCentre: {
      type: [Number], // [lng, lat]
    },
    suggestedRadiusKm: {
      type: Number,
      default: 10,
    },

    status: {
      type: String,
      enum: AI_ALERT_STATUSES,
      default: 'pending_review',
      index: true,
    },

    reviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'AdminUser',
    },

    reviewedByName: {
      type: String,
      trim: true,
    },

    reviewedAt: Date,

    reviewNotes: {
      type: String,
      trim: true,
    },

    // Link to the published DisasterEvent if promoted
    linkedEventId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'DisasterEvent',
    },
  },
  {
    timestamps: true,
  }
);

aiAlertSchema.index({ status: 1, createdAt: -1 });
aiAlertSchema.index({ district: 1, status: 1 });

module.exports = mongoose.model('AiAlert', aiAlertSchema);
module.exports.AI_ALERT_STATUSES = AI_ALERT_STATUSES;
