/**
 * AI Alerts Routes — /api/ai-alerts
 *
 * Manages anomaly detections and alert proposals generated by the AI service.
 * Supports human-in-the-loop review, promoting to DisasterEvent, and dismissal.
 */

const express = require('express');
const { body, param, query } = require('express-validator');
const AiAlert = require('../models/AiAlert');
const DisasterEvent = require('../models/DisasterEvent');
const { protect, requireRole } = require('../middleware/auth');
const validate = require('../middleware/validate');
const alertService = require('../services/alertService');

const router = express.Router();

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/ai-alerts — List AI alerts
// ─────────────────────────────────────────────────────────────────────────────
router.get(
  '/',
  protect,
  [
    query('status').optional().isIn(['pending_review', 'approved_into_event', 'dismissed', 'escalated', 'all']),
    query('district').optional().isString(),
    query('hazardType').optional().isString(),
    query('limit').optional().isInt({ min: 1, max: 100 }),
  ],
  validate,
  async (req, res, next) => {
    try {
      const status = req.query.status || 'pending_review';
      const limit = parseInt(req.query.limit) || 50;

      const filter = {};
      if (status !== 'all') filter.status = status;
      if (req.query.district) filter.district = req.query.district;
      if (req.query.hazardType) filter.hazardType = req.query.hazardType;

      const alerts = await AiAlert.find(filter)
        .populate('linkedEventId', 'title status severity')
        .populate('reviewedBy', 'name email role')
        .sort({ score: -1, createdAt: -1 })
        .limit(limit)
        .lean();

      res.json({
        success: true,
        count: alerts.length,
        alerts,
      });
    } catch (err) {
      next(err);
    }
  }
);

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/ai-alerts/ingest — Ingest proposed alerts from AI Service
// ─────────────────────────────────────────────────────────────────────────────
router.post(
  '/ingest',
  [
    body('state').notEmpty().withMessage('State is required'),
    body('district').notEmpty().withMessage('District is required'),
    body('hazardType').notEmpty().withMessage('hazardType is required'),
    body('score').isFloat({ min: 0, max: 1 }).withMessage('Score must be between 0 and 1'),
    body('explanation').notEmpty().withMessage('Explanation is required'),
  ],
  validate,
  async (req, res, next) => {
    try {
      const alert = await AiAlert.create(req.body);
      res.status(201).json({
        success: true,
        message: 'AI alert proposal created',
        alert,
      });
    } catch (err) {
      next(err);
    }
  }
);

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/ai-alerts/:id/promote — Promote AI Alert to DisasterEvent
// Converts proposal to a live or pending disaster event.
// ─────────────────────────────────────────────────────────────────────────────
router.post(
  '/:id/promote',
  protect,
  [
    param('id').isMongoId().withMessage('Invalid AI alert ID'),
    body('targetStatus').optional().isIn(['draft', 'pending_approval', 'approved', 'published', 'active']),
    body('customTitle').optional().isString().isLength({ max: 120 }),
    body('customDescription').optional().isString(),
    body('radiusKm').optional().isFloat({ min: 0.5, max: 1000 }),
    body('hindiTitle').optional().isString(),
    body('hindiDescription').optional().isString(),
  ],
  validate,
  async (req, res, next) => {
    try {
      const aiAlert = await AiAlert.findById(req.params.id);
      if (!aiAlert) {
        return res.status(404).json({ success: false, message: 'AI alert not found' });
      }

      if (aiAlert.status === 'approved_into_event') {
        return res.status(409).json({
          success: false,
          message: 'This AI alert has already been promoted to an event',
          linkedEventId: aiAlert.linkedEventId,
        });
      }

      const targetStatus = req.body.targetStatus || 'pending_approval';

      // Default district coordinates mapping for northern India / UP
      const DISTRICT_COORDS = {
        Varanasi: [82.9739, 25.3176],
        Gorakhpur: [83.3732, 26.7606],
        Prayagraj: [81.8463, 25.4358],
        Lucknow: [80.9462, 26.8467],
        Ayodhya: [82.1998, 26.7922],
        Kanpur: [80.3319, 26.4499],
        Mirzapur: [82.5644, 25.1337],
        Ballia: [84.1497, 25.7582],
      };

      const centreCoords = aiAlert.suggestedCentre && aiAlert.suggestedCentre.length === 2
        ? aiAlert.suggestedCentre
        : DISTRICT_COORDS[aiAlert.district] || [82.9739, 25.3176];

      const radiusKm = req.body.radiusKm || aiAlert.suggestedRadiusKm || 15;

      const title = req.body.customTitle ||
        `[AI Early Warning] ${aiAlert.hazardType} Alert in ${aiAlert.district}`;

      const description = req.body.customDescription ||
        `${aiAlert.explanation} Citizens in ${aiAlert.district} should remain vigilant and monitor advisories.`;

      // Create new DisasterEvent
      const event = await DisasterEvent.create({
        title,
        type: aiAlert.hazardType,
        severity: aiAlert.recommendedSeverity || 'Watch',
        description,
        targetStates: [aiAlert.state],
        targetDistricts: [aiAlert.district],
        state: aiAlert.state,
        district: aiAlert.district,
        translations: {
          hi: {
            title: req.body.hindiTitle || `[चेतावनी] ${aiAlert.district} में ${aiAlert.hazardType} का खतरा`,
            description: req.body.hindiDescription || `${aiAlert.district} में अलर्ट जारी। कृपया सुरक्षित स्थान पर रहें।`,
          },
        },
        zoneType: 'radius',
        centre: {
          type: 'Point',
          coordinates: centreCoords,
        },
        radiusKm,
        bufferRadiusKm: 5,
        status: targetStatus,
        createdBy: req.admin._id,
        approvalWorkflow: {
          submittedBy: req.admin._id,
          submittedAt: new Date(),
          ...(targetStatus === 'published' || targetStatus === 'active'
            ? { approvedBy: req.admin._id, approvedAt: new Date(), reviewNotes: 'Directly published from AI proposal' }
            : {}),
        },
      });

      // Update AI Alert state
      aiAlert.status = 'approved_into_event';
      aiAlert.reviewedBy = req.admin._id;
      aiAlert.reviewedAt = new Date();
      aiAlert.linkedEventId = event._id;
      await aiAlert.save();

      // If directly published, dispatch alerts immediately
      if (targetStatus === 'published' || targetStatus === 'active') {
        alertService.dispatchAlerts(event).catch((err) =>
          console.error('[AiAlerts] Auto-dispatch failed on direct promote:', err.message)
        );
      }

      res.status(201).json({
        success: true,
        message: `AI alert promoted to event (${targetStatus})`,
        event,
        aiAlert,
      });
    } catch (err) {
      next(err);
    }
  }
);

// ─────────────────────────────────────────────────────────────────────────────
// PATCH /api/ai-alerts/:id/dismiss — Dismiss AI Alert as false positive
// ─────────────────────────────────────────────────────────────────────────────
router.patch(
  '/:id/dismiss',
  protect,
  [
    param('id').isMongoId().withMessage('Invalid AI alert ID'),
    body('notes').optional().isString().isLength({ max: 500 }),
  ],
  validate,
  async (req, res, next) => {
    try {
      const aiAlert = await AiAlert.findById(req.params.id);
      if (!aiAlert) {
        return res.status(404).json({ success: false, message: 'AI alert not found' });
      }

      aiAlert.status = 'dismissed';
      aiAlert.reviewedBy = req.admin._id;
      aiAlert.reviewedAt = new Date();
      aiAlert.reviewNotes = req.body.notes || 'Dismissed as non-threatening anomaly by operator';
      await aiAlert.save();

      res.json({
        success: true,
        message: 'AI alert dismissed',
        aiAlert,
      });
    } catch (err) {
      next(err);
    }
  }
);

module.exports = router;
